name: ci
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false

      # - uses: bahmutov/npm-install@v1
      # - run: npm run docs:build

      - uses: cypress-io/github-action@v1
        name: test local dev site
        with:
          build: 'npm run docs:build'
          start: 'npm run docs:dev'
          wait-on: 'http://localhost:8080/triple-tested/'

      # https://github.com/marketplace/actions/github-pages-action
      - name: Deploy 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/.vuepress/dist
