name: deployed
on: status
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # - name: Dump GitHub context
      #   env:
      #     GITHUB_CONTEXT: ${{ toJson(github) }}
      #   run: echo "$GITHUB_CONTEXT"

      - name: check if built
        if: github.event.context == 'github/pages' && github.event.state == 'success'
        run: |
          echo "gh-pages 📑 built successfully ✅"
          curl https://glebbahmutov.com/triple-tested/
