name: deployed
on:
  status:
    branches:
      - master
jobs:
  test-deployed-page:
    if: github.event.context == 'github/pages' && github.event.state == 'success'
    runs-on: ubuntu-latest
    env:
      CYPRESS_baseUrl: https://glebbahmutov.com/triple-tested/
    steps:
      - run: echo "gh-pages 📑 built successfully ✅"
      - name: show deployed page
        run: curl -s $CYPRESS_baseUrl

      # we need our source code that has package.json and Cypress specs
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      # https://github.com/cypress-io/github-action
      - uses: cypress-io/github-action@v1
        name: test deployed site
        record: true
        tag: 'production'
      env:
        CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
